# Generated by Django 4.2.1 on 2023-11-16 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'Product'},
        ),
    ]
