# Generated by Django 4.2.1 on 2023-11-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
